version: 0.0
os: linux

hooks:
  ApplicationInstall:
    - location: scripts/install_pm2.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 300
      runas: root
