# version: 0.0
# os: linux

# hooks:
#   ApplicationInstall:
#     - location: scripts/install_pm2.sh
#       timeout: 300
#       runas: root

#   ApplicationStart:
#     - location: scripts/start_pm2.sh
#       timeout: 300
#       runas: root


version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/three-tier-app-code/frontend
    overwrite: true

hooks:
  AfterInstall:
    - location: scripts/install_pm2.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 300
      runas: root
