version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - docker build -t my-frontend ./frontend
      - docker build -t my-backend ./backend
      - docker tag my-frontend:latest ankitrawat3987/my-frontend:latest
      - docker tag my-backend:latest ankitrawat3987/my-backend:latest
  post_build:
    commands:
      - docker push ankitrawat3987/my-frontend:latest
      - docker push ankitrawat3987/my-backend:latest
      - printf '[{"name":"frontend","imageUri":"%s"},{"name":"backend","imageUri":"%s"}]' \
         ankitrawat3987/my-frontend:latest ankitrawat3987/my-backend:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
