version: 0.2

# env:
#   secrets-manager:
#     DOCKERHUB_USERNAME: "/docker-cred/:username"
#     DOCKERHUB_PASSWORD: "/docker-cred/:password"

phases:
  install:
    commands:
      - echo Installing npm...
      - sudo apt update
      - sudo apt install npm -y
      # # - yum update
      # - dnf update
      # - yum install npm -y
      - npm -version
  
  build:
    commands:
      - echo Building frontend...
      - cd frontend
      - npm i
      # - npm start
      # - cd ..
      # - echo Building backend Docker image...
      # - cd backend
      # - docker build -t "$DOCKERHUB_USERNAME/backend:$CODEBUILD_RESOLVED_SOURCE_VERSION" .
      # - cd ..

  # post_build:
  #   commands:
  #     - echo Pushing frontend Docker image to Docker Hub...
  #     - docker push "$DOCKERHUB_USERNAME/frontend:$CODEBUILD_RESOLVED_SOURCE_VERSION"
  #     - echo Pushing backend Docker image to Docker Hub...
  #     - docker push "$DOCKERHUB_USERNAME/backend:$CODEBUILD_RESOLVED_SOURCE_VERSION"

artifacts:
  files:
    - '**/*'
