version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "/docker-cred/:username"
    DOCKERHUB_PASSWORD: "/docker-cred/:password"

phases:
  install:
    commands:
      - echo Installing docker...
      - apt install -y docker
      - docker --version
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo Building frontend Docker image...
      - cd frontend
      - docker build -t "$DOCKERHUB_USERNAME/frontend:$CODEBUILD_RESOLVED_SOURCE_VERSION" .
      - cd ..
      - echo Building backend Docker image...
      - cd backend
      - docker build -t "$DOCKERHUB_USERNAME/backend:$CODEBUILD_RESOLVED_SOURCE_VERSION" .
      - cd ..

  post_build:
    commands:
      - echo Pushing frontend Docker image to Docker Hub...
      - docker push "$DOCKERHUB_USERNAME/frontend:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo Pushing backend Docker image to Docker Hub...
      - docker push "$DOCKERHUB_USERNAME/backend:$CODEBUILD_RESOLVED_SOURCE_VERSION"

artifacts:
  files:
    - '**/*'
