version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node and npm are preinstalled:"
      - node -v
      - npm -v

  build:
    commands:
      - echo "Building frontend..."
      - cd frontend
      - npm install

artifacts:
  files:
    - '**/*'

# version: 0.2
# phases:
#   install:
#     commands:
#       - echo Installing npm...
#       - sudo apt update
#       - sudo apt install npm -y
#       # # - yum update
#       # - dnf update
#       # - yum install npm -y
#       - npm -version
  
#   build:
#     commands:
#       - echo Building frontend...
#       - cd frontend
#       - npm i
#       # - npm start
#       # - cd ..
#       # - echo Building backend Docker image...
#       # - cd backend
#       # - docker build -t "$DOCKERHUB_USERNAME/backend:$CODEBUILD_RESOLVED_SOURCE_VERSION" .
#       # - cd ..
      
# artifacts:
#   files:
#     - '**/*'
